services:
  nginx:
    hostname: :tmp:_web_server
    image: nginx:latest
    container_name: :tmp:_nginx
    ports:
      - "80:80"
      - "8080:8080"
    restart: no
    networks:
      - :tmp:_networks
    depends_on:
      - app
    volumes:
      - ./:/src
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  mysql:
    hostname: :tmp:_db_server
    image: mysql:latest
    container_name: :tmp:_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: :tmp:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/mysql-data:/var/lib/mysql"
      - ./storage/logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    restart: no
    networks:
      - :tmp:_networks
  app:
    hostname: :tmp:_app_server
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: :tmp:_app
    environment:
      COMPOSER_MEMORY_LIMIT: '-1'
    ports:
      - "9912:9912"
      - "5173:5173"
    restart: no
    networks:
      - :tmp:_networks
    working_dir: /src
    volumes:
      - ./:/src:cached
  phpmyadmin:
    hostname: :tmp:_phpmyadmin_server
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: :tmp:_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "3000:80"
    restart: no
    networks:
      - :tmp:_networks
    environment:
      PMA_HOST: :tmp:_db_server
      PMA_USER: root
      PMA_PASSWORD: password
      MEMORY_LIMIT: 256M
      UPLOAD_LIMIT: 128M

networks:
  default:
    external: true
    name: bridge
  :tmp:_networks:
    name: :tmp:.internal